export enum ApiCodeResponse {
    TEST = 'api.result.test',
    NO_TOKEN_FOUNDED = "NO_TOKEN_FOUNDED",
    USER_NOT_FOUND = "USER_NOT_FOUND",
    TOKEN_EXPIRED = "TOKEN_EXPIRED",
    SIGNUP_ERROR = "SIGNUP_ERROR",
    CREDENTIAL_DELETE_ERROR = "CREDENTIAL_DELETE_ERROR",
    USER_ALREADY_EXIST = "USER_ALREADY_EXIST",
    TOKEN_GEN_ERROR = "TOKEN_GEN_ERROR",
    PAYLOAD_IS_NOT_VALID = "PAYLOAD_IS_NOT_VALID",
    COMMON_SUCCESS = "COMMON_SUCCESS",
    PAYLOAD_PARAM_IS_MISSING = "PAYLOAD_PARAM_IS_MISSING"
}